version: '3.7'

x-dbenv: &dbenv
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: db


services:
  cache:
    image: redis:alpine
    container_name: standards_redis
    expose:
      - 6379

  db:
    image: postgres:10.1-alpine
    container_name: standards_db
    environment: *dbenv
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  backend:
    build: .
    container_name: standards_server
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    # && python manage.py makemessages --all -e py,html,jinja
    environment: 
      <<: *dbenv
      DJANGO_DB_URL: psql://postgres:postgres@db:5432/db
      DJANGO_CACHE_URL: redis://cache:6379
      CELERY_BROKER_URL: redis://cache:6379
    ports:
      - 8000:8000
    volumes:
      - ./:/code/
      - ../standards/:/code/standards/
    depends_on:
      - db
      - cache
    links:
      - db:db
      - cache:redis


volumes:
  postgres_data:
